<?php
try {
    // Connect to MySQL server
    $bd = new PDO("mysql:host=localhost", "root", "");
    $bd->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

    // Create database
    $bd->exec("CREATE DATABASE IF NOT EXISTS STOCKIFY_DATABASE");
    $bd->exec("USE STOCKIFY_DATABASE");

    // SQL commands to execute
    $sqlCommands = [
        // Drop Tables with Foreign Keys First
        "DROP TABLE IF EXISTS DEVIS_DETAILS",
        "DROP TABLE IF EXISTS DEVIS_HEADER",
        "DROP TABLE IF EXISTS SELL_INVOICE_DETAILS",
        "DROP TABLE IF EXISTS SELL_INVOICE_HEADER",
        "DROP TABLE IF EXISTS BON_LIVRAISON_DETAILS",
        "DROP TABLE IF EXISTS BON_LIVRAISON_HEADER",
        "DROP TABLE IF EXISTS BON_COMMANDE_DETAILS",
        "DROP TABLE IF EXISTS BON_COMMANDE_HEADER",
        "DROP TABLE IF EXISTS BUY_INVOICE_DETAILS",
        "DROP TABLE IF EXISTS BUY_INVOICE_HEADER",
        "DROP TABLE IF EXISTS PRODUCT",
        "DROP TABLE IF EXISTS USERS",

        // Drop Remaining Tables
        "DROP TABLE IF EXISTS CLIENT",
        "DROP TABLE IF EXISTS SUPPLIER",
        "DROP TABLE IF EXISTS CATEGORY",
        "DROP TABLE IF EXISTS ROLES",
        "DROP TABLE IF EXISTS GENERAL_VARIABLES",

        // Create Tables
        "CREATE TABLE GENERAL_VARIABLES(
            ID INTEGER PRIMARY KEY,
            TVA_AMOUNT DECIMAL(10,2) DEFAULT 20.00
        )",

        "CREATE TABLE ROLES(
            ID INTEGER PRIMARY KEY AUTO_INCREMENT,
            ROLE_ID VARCHAR(16) UNIQUE NOT NULL,
            NAME VARCHAR(30) NOT NULL,
            NUMBER_OF_USERS INTEGER DEFAULT 0,
            ADMINISTRATOR INTEGER(1) DEFAULT 0,
            VIEW_PRODUCTS INTEGER(1) DEFAULT 0,
            ADD_PRODUCTS INTEGER(1) DEFAULT 0,
            MODIFY_PRODUCTS INTEGER(1) DEFAULT 0,
            DELETE_PRODUCTS INTEGER(1) DEFAULT 0,
            VIEW_CATEGORIES INTEGER(1) DEFAULT 0,
            ADD_CATEGORIES INTEGER(1) DEFAULT 0,
            MODIFY_CATEGORIES INTEGER(1) DEFAULT 0,
            DELETE_CATEGORIES INTEGER(1) DEFAULT 0,
            VIEW_INVOICES INTEGER(1) DEFAULT 0,
            ADD_INVOICES INTEGER(1) DEFAULT 0,
            MODIFY_INVOICES INTEGER(1) DEFAULT 0,
            DELETE_INVOICES INTEGER(1) DEFAULT 0,
            VIEW_USERS INTEGER(1) DEFAULT 0,
            ADD_USERS INTEGER(1) DEFAULT 0,
            MODIFY_USERS INTEGER(1) DEFAULT 0,
            DELETE_USERS INTEGER(1) DEFAULT 0,
            VIEW_ROLES INTEGER(1) DEFAULT 0,
            ADD_ROLES INTEGER(1) DEFAULT 0,
            MODIFY_ROLES INTEGER(1) DEFAULT 0,
            DELETE_ROLES INTEGER(1) DEFAULT 0,
            VIEW_ORDERS INTEGER(1) DEFAULT 0,
            ADD_ORDERS INTEGER(1) DEFAULT 0,
            MODIFY_ORDERS INTEGER(1) DEFAULT 0,
            DELETE_ORDERS INTEGER(1) DEFAULT 0,
            VIEW_QUOTATIONS INTEGER(1) DEFAULT 0,
            ADD_QUOTATIONS INTEGER(1) DEFAULT 0,
            CONFIRM_QUOTATIONS INTEGER(1) DEFAULT 0,
            DELETE_QUOTATIONS INTEGER(1) DEFAULT 0,
            VIEW_CLIENTS INTEGER(1) DEFAULT 0,
            DELETE_CLIENTS INTEGER(1) DEFAULT 0,
            VIEW_SUPPLIERS INTEGER(1) DEFAULT 0,
            ADD_SUPPLIERS INTEGER(1) DEFAULT 0,
            DELETE_SUPPLIERS INTEGER(1) DEFAULT 0,
            USE_AI INTEGER(1) DEFAULT 0,
            STATE_INITIATED INTEGER(1) DEFAULT 0,
            STATE_IN_PROGRESS INTEGER(1) DEFAULT 0,
            STATE_DELIVERING INTEGER(1) DEFAULT 0,
            STATE_HALTED INTEGER(1) DEFAULT 0,
            STATE_DELIVERED INTEGER(1) DEFAULT 0,
            STATE_CANCELED INTEGER(1) DEFAULT 0
        )",

        "CREATE TABLE USERS(
            ID INTEGER PRIMARY KEY AUTO_INCREMENT,
            USER_ID VARCHAR(16) UNIQUE NOT NULL,
            LAST_NAME VARCHAR(30),
            FIRST_NAME VARCHAR(30),
            USERNAME VARCHAR(30) UNIQUE NOT NULL,
            USER_ROLE_ID VARCHAR(16),
            TELEPHONE VARCHAR(10) NOT NULL,
            EMAIL VARCHAR(255),
            USER_PASSWORD VARCHAR(255),
            CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            FOREIGN KEY (USER_ROLE_ID) REFERENCES ROLES(ROLE_ID)
                ON DELETE SET NULL
        )",

        "CREATE TABLE CATEGORY(
            ID INTEGER PRIMARY KEY AUTO_INCREMENT,
            CATEGORYNAME VARCHAR(30) UNIQUE NOT NULL,
            IMAGE LONGBLOB DEFAULT NULL,
            NUMBER_OF_PRODUCTS INTEGER DEFAULT 0
        )",

        "INSERT INTO CATEGORY(CATEGORYNAME) VALUES('Uncategorized')",

        "CREATE TABLE SUPPLIER(
            ID INTEGER PRIMARY KEY AUTO_INCREMENT,
            SUPPLIERNAME VARCHAR(255) UNIQUE NOT NULL,
            ICE VARCHAR(15) UNIQUE DEFAULT NULL
        )",

        "CREATE TABLE CLIENT(
            ID INTEGER PRIMARY KEY AUTO_INCREMENT,
            CLIENTNAME VARCHAR(255) NOT NULL DEFAULT 'Client comptoir',
            ICE VARCHAR(15) UNIQUE
        )",

        "CREATE TABLE PRODUCT(
            ID INTEGER PRIMARY KEY AUTO_INCREMENT,
            REFERENCE VARCHAR(16) UNIQUE NOT NULL,
            PRODUCT_NAME VARCHAR(255) NOT NULL,
            PRICE DECIMAL(10, 2) DEFAULT 0.00,
            QUANTITY INTEGER DEFAULT 0,
            CATEGORY_NAME VARCHAR(30) DEFAULT 'Uncategorized',
            IMAGE LONGBLOB,
            FOREIGN KEY (CATEGORY_NAME) REFERENCES CATEGORY(CATEGORYNAME)
                ON UPDATE CASCADE
                ON DELETE SET NULL
        )",

        "CREATE TABLE BUY_INVOICE_HEADER(
            ID_INVOICE INTEGER PRIMARY KEY AUTO_INCREMENT,
            INVOICE_NUMBER VARCHAR(30) UNIQUE NOT NULL,
            SUPPLIER_NAME VARCHAR(255),
            TOTAL_PRICE_TTC DECIMAL(10, 2) DEFAULT 0.00,
            TOTAL_PRICE_HT DECIMAL(10, 2) DEFAULT 0.00,
            TOTAL_PRICE_TVA DECIMAL(10, 2) DEFAULT 0.00,
            DATE DATE DEFAULT CURRENT_DATE,
            IMAGE LONGBLOB DEFAULT NULL,
            FOREIGN KEY (SUPPLIER_NAME) REFERENCES SUPPLIER(SUPPLIERNAME)
                ON UPDATE CASCADE
                ON DELETE CASCADE
        )",

        "CREATE TABLE BUY_INVOICE_DETAILS (
            ID_DETAIL INTEGER PRIMARY KEY AUTO_INCREMENT,
            ID_INVOICE INTEGER,
            PRODUCT_ID VARCHAR(16),
            PRODUCT_NAME VARCHAR(255),
            QUANTITY INTEGER,
            UNIT_PRICE_TTC DECIMAL(10, 2),
            TOTAL_PRICE DECIMAL(10, 2),
            FOREIGN KEY (ID_INVOICE) REFERENCES BUY_INVOICE_HEADER(ID_INVOICE)
                ON UPDATE CASCADE
                ON DELETE CASCADE,
            FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(REFERENCE)
                ON UPDATE CASCADE
                ON DELETE SET NULL
        )",

        "CREATE TABLE BON_COMMANDE_HEADER(
            ID INTEGER PRIMARY KEY AUTO_INCREMENT,
            ID_COMMANDE VARCHAR(16) NOT NULL UNIQUE,
            CLIENT_ID INTEGER,
            CLIENT_NAME VARCHAR(255),
            COMPANY_ICE VARCHAR(15),
            ADDRESSE VARCHAR(50),
            TYPE VARCHAR(16) DEFAULT 'Personal' NOT NULL,
            STATE ENUM('initiated', 'in progress', 'delivering', 'halted', 'delivered', 'canceled') DEFAULT 'initiated',
            DATE DATE NOT NULL DEFAULT CURRENT_DATE,
            TOTAL_PRICE_TTC DECIMAL(10, 2) DEFAULT 0.00,
            FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT(ID)
                ON UPDATE CASCADE
                ON DELETE CASCADE
        )",

        "CREATE TABLE BON_COMMANDE_DETAILS(
            ID_DETAIL INTEGER PRIMARY KEY AUTO_INCREMENT,
            ID_COMMANDE INTEGER,
            COMMANDE_NUMBER VARCHAR(16),
            PRODUCT_ID VARCHAR(16),
            QUANTITY INTEGER NOT NULL DEFAULT 0,
            DELIVERED_QUANTITY INTEGER NOT NULL DEFAULT 0,
            UNIT_PRICE_TTC DECIMAL(10,2) DEFAULT 0.00,
            TOTAL_PRICE_TTC DECIMAL(10,2) DEFAULT 0.00,
            FOREIGN KEY (ID_COMMANDE) REFERENCES BON_COMMANDE_HEADER(ID)
                ON UPDATE CASCADE
                ON DELETE CASCADE,
            FOREIGN KEY (COMMANDE_NUMBER) REFERENCES BON_COMMANDE_HEADER(ID_COMMANDE)
                ON UPDATE CASCADE
                ON DELETE CASCADE,
            FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(REFERENCE)
                ON UPDATE CASCADE
                ON DELETE SET NULL
        )",

        "CREATE TABLE BON_LIVRAISON_HEADER(
            ID INTEGER PRIMARY KEY AUTO_INCREMENT,
            ID_BON VARCHAR(16) UNIQUE NOT NULL,
            ID_COMMANDE INTEGER,
            CLIENT_NAME VARCHAR(255),
            COMPANY_ICE VARCHAR(15),
            INVOICE_TYPE VARCHAR(16) DEFAULT 'Personal' NOT NULL,
            TOTAL_PRICE_TTC DECIMAL(10, 2) DEFAULT 0.00,
            TOTAL_PRICE_HT DECIMAL(10, 2) DEFAULT 0.00,
            TVA DECIMAL(10,2) DEFAULT 0.00,
            DATE DATE DEFAULT CURRENT_DATE,
            FOREIGN KEY (ID_COMMANDE) REFERENCES BON_COMMANDE_HEADER(ID)
                ON UPDATE CASCADE
                ON DELETE CASCADE
        )",

        "CREATE TABLE BON_LIVRAISON_DETAILS(
            ID_DETAIL INTEGER PRIMARY KEY AUTO_INCREMENT,
            ID_BON INTEGER,
            PRODUCT_ID VARCHAR(16),
            PRODUCT_NAME VARCHAR(255),
            QUANTITY INTEGER NOT NULL,
            UNIT_PRICE_TTC DECIMAL(10, 2) DEFAULT 0.00,
            TOTAL_PRICE_TTC DECIMAL(10, 2) DEFAULT 0.00,
            FOREIGN KEY (ID_BON) REFERENCES BON_LIVRAISON_HEADER(ID)
                ON UPDATE CASCADE
                ON DELETE CASCADE,
            FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(REFERENCE)
                ON UPDATE CASCADE
                ON DELETE SET NULL
        )",

        "CREATE TABLE SELL_INVOICE_HEADER(
            ID_INVOICE INTEGER PRIMARY KEY AUTO_INCREMENT,
            INVOICE_NUMBER VARCHAR(16) UNIQUE NOT NULL,
            ID_BON_LIVRAISON INTEGER,
            CLIENT_NAME VARCHAR(255),
            COMPANY_ICE VARCHAR(15),
            INVOICE_TYPE VARCHAR(16) DEFAULT 'Personal' NOT NULL,
            TOTAL_PRICE_TTC DECIMAL(10, 2) DEFAULT 0.00,
            TOTAL_PRICE_HT DECIMAL(10, 2) DEFAULT 0.00,
            TVA DECIMAL(10,2) DEFAULT 0.00,
            PAYEMENT ENUM('Espece', 'Cheque', 'Effet'),
            PAYEMENT_REFERENCE VARCHAR(50),
            DATE DATE DEFAULT CURRENT_DATE,
            EARNINGS DECIMAL(10,2) DEFAULT 0.00,
            FOREIGN KEY (ID_BON_LIVRAISON) REFERENCES BON_LIVRAISON_HEADER(ID)
                ON UPDATE CASCADE
                ON DELETE CASCADE
        )",

        "CREATE TABLE SELL_INVOICE_DETAILS(
            ID_DETAIL INTEGER PRIMARY KEY AUTO_INCREMENT,
            ID_INVOICE INTEGER,
            PRODUCT_ID VARCHAR(16),
            PRODUCT_NAME VARCHAR(255),
            QUANTITY INTEGER,
            UNIT_PRICE_TTC DECIMAL(10, 2) DEFAULT 0.00,
            TOTAL_PRICE_TTC DECIMAL(10, 2) DEFAULT 0.00,
            FOREIGN KEY (ID_INVOICE) REFERENCES SELL_INVOICE_HEADER(ID_INVOICE)
                ON UPDATE CASCADE
                ON DELETE CASCADE,
            FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(REFERENCE)
                ON UPDATE CASCADE
                ON DELETE SET NULL
        )",

        "CREATE TABLE DEVIS_HEADER(
            ID INTEGER PRIMARY KEY AUTO_INCREMENT,
            DEVIS_NUMBER VARCHAR(16) UNIQUE NOT NULL,
            CLIENT_ID INTEGER,
            CLIENT_NAME VARCHAR(255),
            COMPANY_ICE VARCHAR(15),
            TOTAL_PRICE_TTC DECIMAL(10, 2) DEFAULT 0.00,
            TOTAL_PRICE_HT DECIMAL(10, 2) DEFAULT 0.00,
            TVA DECIMAL(10,2) DEFAULT 0.00,
            DATE DATE DEFAULT CURRENT_DATE,
            FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT(ID)
                ON UPDATE CASCADE
                ON DELETE CASCADE
        )",

        "CREATE TABLE DEVIS_DETAILS (
            ID_DETAIL INTEGER PRIMARY KEY AUTO_INCREMENT,
            ID_DEVIS INTEGER,
            PRODUCT_ID VARCHAR(16),
            QUANTITY INTEGER,
            UNIT_PRICE_TTC DECIMAL(10, 2) DEFAULT 0.00,
            TOTAL_PRICE_TTC DECIMAL(10, 2) DEFAULT 0.00,
            FOREIGN KEY (ID_DEVIS) REFERENCES DEVIS_HEADER(ID)
                ON UPDATE CASCADE
                ON DELETE CASCADE,
            FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(REFERENCE)
                ON UPDATE CASCADE
                ON DELETE SET NULL
        )",

        // Insert data for ROLES
        "INSERT INTO ROLES (ROLE_ID, NAME, ADMINISTRATOR, VIEW_USERS, ADD_USERS, MODIFY_USERS, DELETE_USERS) VALUES
        ('0', 'Super Admin', 1,0,0,0,0),
        ('1', 'Admin', 0,1,1,1,1),
        ('2', 'User', 0,0,0,0,0)",

        // Insert default admin account
        "INSERT INTO USERS (USER_ID, USERNAME, USER_PASSWORD, USER_ROLE_ID, TELEPHONE, EMAIL, FIRST_NAME, LAST_NAME)
        VALUES ('U0', 'admin', 'admin123', '0', '0000000000', 'admin@example.com', 'Admin', 'User')",

        // Insert data for GENERAL VARIABLES
        "INSERT INTO GENERAL_VARIABLES(ID, TVA_AMOUNT) VALUES(1, 20.00)",

        // Update roles data if users exist
        "UPDATE ROLES r
        JOIN (
          SELECT USER_ROLE_ID, COUNT(*) AS user_count
          FROM USERS
          GROUP BY USER_ROLE_ID
        ) counts ON r.ROLE_ID = counts.USER_ROLE_ID
        SET r.NUMBER_OF_USERS = counts.user_count",
    ];

    // Execute each SQL command
    foreach ($sqlCommands as $sql) {
        try {
            $bd->exec($sql);
        } catch (PDOException $e) {
            echo "Error executing SQL: " . $e->getMessage() . "<br>";
            echo "SQL that caused the error: " . $sql . "<br><br>";
        }
    }

    echo "Database setup completed successfully!";
} catch (PDOException $e) {
    die("Database error: " . $e->getMessage());
}

// w ta7ia 3askaria l deepseek

?>
